src/MvcVehicle/Models/Vehicle.cs
using System;
using System.ComponentModel.DataAnnotations;



namespace MvcVehicle.Models
{
    public class Vehicle
    {
        public int ID { get; set; }

        [StringLength(60, MinimumLength =3), Display(Name ="Car Model")]
        public string CarModel { get; set; }

        [DisplayFormat(DataFormatString= "{0:yyyy-MM}", ApplyFormatInEditMode = true), DataType(DataType.Date)]
        public DateTime SOP { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$"), Required , StringLength(30)]
        public string Maker { get; set; }

        [Range(1,10000)]
        public decimal EGsize { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$") ,StringLength(30)]
        public string Transmission { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$") ,StringLength(30)]
        public string Hybrid { get; set; }

    }
}

src/MvcVehicle/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcVehicle.Data;
using MvcVehicle.Models;

namespace MvcVehicle.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VehiclesController(ApplicationDbContext context)
        {
            _context = context;    
        }

 /*       // GET: Vehicles
        public async Task<IActionResult> Index(string searchString)
        {
            var vehicles = from p in _context.Vehicle
                           select p;

            if(!String.IsNullOrEmpty(searchString))
            {
                vehicles = vehicles.Where(k => k.CarModel.Contains(searchString));
            }
            return View(await vehicles.ToListAsync());
        }
 */
        public async Task<IActionResult> Index(string carMakersearch, string searchstring)
        {
            // Use LINQ to get list of makers
            IQueryable<string> makerQuery = from z in _context.Vehicle
                                            orderby z.Maker
                                            select z.Maker;
            var vehicles = from z in _context.Vehicle
                           select z;

            if (!String.IsNullOrEmpty(searchstring))
            {
                vehicles = vehicles.Where(m => m.CarModel.Contains(searchstring));              
            }

            if (!String.IsNullOrEmpty(carMakersearch))
            {
                vehicles = vehicles.Where(j => j.Maker == carMakersearch);
            }

            var carModelVM = new CarMakerViewModel();
            carModelVM.makers = new SelectList(await makerQuery.Distinct().ToListAsync());
            carModelVM.vehicles = await vehicles.ToListAsync();

            return View(carModelVM);
        }




        // POST: Vehicles    
        [HttpPost]
        public string Index(string searchString, bool notused)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }



        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.SingleOrDefaultAsync(m => m.ID == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }



        // GET: Vehicles/Create
        public IActionResult Create()
        {
            return View();
        }
                
        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CarModel,EGsize,Maker,SOP")] Vehicle vehicle)
        {

/*            //Validate Google recaptcha here
            var response = Request["g-recaptcha-response"];
            string secretKey = "6LclxSgTAAAAANWxsVaVQVEKis_-rEuHi4ChpKDK";
            var result = DownloadString(string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secretKey, response));
            var obj = Newtonsoft.Json.Linq.JObject.Parse(result);
            var status = (bool)obj.SelectToken("success");


            //When you will post form for save data, you should check both the model validation and google recaptcha validation
            //EX.
            /* if (ModelState.IsValid && status)
            {

            }*/

            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }



        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.SingleOrDefaultAsync(m => m.ID == id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CarModel,EGsize,Maker,SOP,Transmission,Hybrid")] Vehicle vehicle)
        {
            if (id != vehicle.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }



        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.SingleOrDefaultAsync(m => m.ID == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }


        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicle = await _context.Vehicle.SingleOrDefaultAsync(m => m.ID == id);
            _context.Vehicle.Remove(vehicle);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicle.Any(e => e.ID == id);
        }
    }
}

src/MvcVehicle/Views/Vehicles/Create.cshtml
@model MvcVehicle.Models.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<head>
    <script src='https://www.google.com/recaptcha/api.js' type="text/javascript"></script>
</head>

<form asp-action="Create" method="post">
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CarModel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EGsize" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EGsize" class="form-control" />
                <span asp-validation-for="EGsize" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Maker" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Maker" class="form-control" />
                <span asp-validation-for="Maker" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SOP" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SOP" class="form-control" />
                <span asp-validation-for="SOP" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Transmission" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Transmission" class="form-control" />
                <span asp-validation-for="Transmission" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Hybrid" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Hybrid" class="form-control" />
                <span asp-validation-for="Hybrid" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="g-recaptcha" data-sitekey="6LclxSgTAAAAACnPltatz1-Up6KU4_5XKWhic72Z"></div>
                <br/>
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/MvcVehicle/Views/Vehicles/Delete.cshtml
@model MvcVehicle.Models.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EGsize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EGsize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Maker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Maker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SOP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SOP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hybrid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hybrid)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/MvcVehicle/Views/Vehicles/Details.cshtml
@model MvcVehicle.Models.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EGsize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EGsize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Maker)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Maker)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SOP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SOP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Transmission)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Transmission)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Hybrid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Hybrid)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/MvcVehicle/Views/Vehicles/Edit.cshtml
@model MvcVehicle.Models.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="CarModel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EGsize" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EGsize" class="form-control" />
                <span asp-validation-for="EGsize" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Maker" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Maker" class="form-control" />
                <span asp-validation-for="Maker" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SOP" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SOP" class="form-control" />
                <span asp-validation-for="SOP" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Transmission" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Transmission" class="form-control" />
                <span asp-validation-for="Transmission" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Hybrid" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Hybrid" class="form-control" />
                <span asp-validation-for="Hybrid" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/MvcVehicle/Views/Vehicles/Index.cshtml
@model CarMakerViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Vehicles" asp-action="Index" method="get">
    <p>
        <select asp-for="carMakersearch" asp-items="Model.makers">
            <option value="">All</option>
        </select>

        Car model: <input type="text" name="searchString" >
        <input type="submit" value="Filter" />
    </p>
</form>





<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].Maker)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].EGsize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].SOP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].CarModel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].Transmission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vehicles[0].Hybrid)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.vehicles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Maker)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EGsize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SOP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Transmission)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hybrid)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>